### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by muhajirframe** [PIWEEK/rethinkscape#3]

**Comment by Xaviju** [comment]
Sorry, is not active anymore
> NOTE This was an experimentation project

**Comment by mateusfccp** [comment]
Why, tho?

**Comment by Xaviju** [comment]
You might want to check this -> https://gitlab.com/inkscape/ux
The inkscape team is doing a great job improving the user experience of the tool. [A great example is the upcoming 1.1 release](https://media.inkscape.org/media/doc/release_notes/1.1/Inkscape_1.1.html)

**Comment by mateusfccp** [comment]
Although Inkscape is always improving, I don't think that it excels in UX yet, and I think that the guidelines proposed by Rethinkscape were appropriate for further improvements!

**Comment by Xaviju** [comment]
The same team behind Rethinkscape has developed Penpot: https://penpot.app/
Penpot goal is not exactly the same as Inkscape, we are focused on interface design, mockup and prototyping, but it might fit your needs.
